### ISSUE TITLE
Invisible in Firefox

### ISSUE THREAD

**Issue by Piskvor** [cyanharlow/PureCSS-Font#1]
In Firefox 59.0.2 (Ubuntu Linux x64), the font is not visible at all - cursor shows, underline shows, elements appear, but apparently they are the same color as the background. Works with Chrome 68 on same computer.

**Comment by Piskvor** [comment]
![screenshot_20180502_180233](https://user-images.githubusercontent.com/917239/39534966-0c245992-4e33-11e8-86c2-6c01092d9681.png)

**Comment by stedko** [comment]
Invisible in firefox.* :(

**Comment by cyanharlow** [comment]
Shit. This is a problem with my JS. Differences in how Firefox handles "keypress" vs. "keydown" vs. "keyup". This is what I get for not just making a damn textarea into which you can paste data and churn out html. I will fix this, though!

**Comment by jerrywham** [comment]
To fix this, instead of `e.keyCode`, you have to use `var r = e.keyCode || e.charCode`.
So the code will work.

```javascript
document.body.addEventListener("keydown", function(e) {
    var r = e.keyCode || e.charCode;
    8 === r || 13 === r || 46 === r ? (e.preventDefault(), listenToKeys(46 === r ? 8 : r)) : r >= 37 && r <= 40 && arrowKeyFunctions(r)
}), document.body.addEventListener("keypress", function(e) {
    var r = e.keyCode || e.charCode;
    listenToKeys(r)
}), document.body.addEventListener("paste", function(e) {
    e.stopPropagation(), e.preventDefault();
    for (var r = e.clipboardData.getData("Text"), t = 0; t < r.length; t++) listenToKeys(r.charCodeAt(t))
}), document.body.addEventListener("click", function(e) {
    if ("texteditor" === e.target.id || "result" === e.target.id ? (result.className = "focused", cursorline.parentNode.removeChild(cursorline), texteditor.lastElementChild.insertAdjacentHTML("beforeend", cursorHTML), Array.prototype.forEach.call(document.querySelectorAll(".AZ"), function(e, r) {
            e.setAttribute("data-azselect", "false")
        })) : result.className = "", "I" === e.target.tagName && 0 === e.target.className.indexOf("AZ") && (result.className = "focused", selectMode = !selectMode, clickPressed = !clickPressed, cursorline.parentNode.removeChild(cursorline), e.target.insertAdjacentHTML("beforebegin", cursorHTML)), "BUTTON" === e.target.tagName && e.target.attributes && e.target.attributes["data-stb"]) {
        var r = e.target.attributes["data-az-style"].nodeValue;
        "selected" === e.target.className ? (texteditor.setAttribute("data-" + r, "0"), e.target.className = "") : (texteditor.setAttribute("data-" + r, "1"), e.target.className = "selected")
    }
});
```

**Comment by cyanharlow** [comment]
@jerrywham You are totally right. I've updated this now - I will have to revisit all the rest of my ugly code to make it better. Also apparently I set my original file to gitignore and I will fix that once I'm  home.

Kids, this is what happens when your Javascript skills don't match your CSS skills. It's the workout equivalent of only doing bench presses. Keep your CSS pecs, but strengthen your Javascript legs!

(I've had very little sleep)

**Comment by jerrywham** [comment]
@cyanharlow I admit I looked a little bit before I found the solution. But that's because I'd already had the same kind of problem with another project. Your work is really impressive and no one will blame you for that little mistake.

**Comment by cyanharlow** [comment]
Finally was able to fix this properly - updated now, let me know if any other problems persist!

**Comment by Piskvor** [comment]
Excellent, thank you!
