### ISSUE TITLE
Not working because of syntax error in generator.min.js

### ISSUE THREAD

**Issue by Ahed91** [cyanharlow/PureCSS-Font#2]
I thinks this error caused by the code uglifying 
line 1 column 988 in generator.min.js
there is a `// e.preventDefault();`  (start of comment) which yield to js syntax error 
   

>  SyntaxError: missing } in compound statement generator.min.js:1:5261 note: { opened at line 1, column 962

**Comment by MarvinXu** [comment]
same.
`Uncaught SyntaxError: Unexpected end of input`

**Comment by jerrywham** [comment]
You're totally right. `// e.preventDefault();` have to be removed. It's a debugging oversight.

**Comment by cyanharlow** [comment]
Finally was able to fix this properly - updated now, let me know if any other problems persist!
