### ISSUE TITLE
Is not 100% hard to catch

### ISSUE THREAD

**Issue by glrodasz** [cyanharlow/PureCSS-Font#5]
Since the classes are the same for each letter is easy to deduce what are the letters. I recommend generating random classes instead.

**Comment by cyanharlow** [comment]
Goddamn, I love that idea.
So with each result it could also generate a string of the corresponding minified CSS and auto-inline it into the head tag?

YES. @glrodasz I am going to make this happen.

**Comment by gazza198810** [comment]
Hello gorgeous

**Comment by cyanharlow** [comment]
Okay anyways.

@glrodasz I loved your suggestion so much that I've dropped the lame text editor portion of the project, now it's extra-randomized and I like it much better.

https://github.com/cyanharlow/PureCSS-Font/commit/d7857b8d8db37c991756e499db7fbf151b3bd66d

**Comment by glrodasz** [comment]
Looks great!
