### ISSUE TITLE
proposal: source files and webpack setup

### ISSUE THREAD

**Issue by DanielRuf** [cyanharlow/PureCSS-Font#6]
It would be great to have the unminified source files and setup some webpack config and publish this on npm.

You can directly start using webpack without any config by default (uses src/index.js) or bootstrap a config with `webpack-cli init`.

And npm on the CLI with `npm init` and `npm publish` is also nice =)

Let me know how we can help you here.

Oh and CI (Travis CI and so on).

Truely great project(s) =)

**Comment by cyanharlow** [comment]
@DanielRuf I love all of that.

I have many lovely backend-specializing colleagues who have been so nice to set up our local environments with an "npm run takecareofeverything" for people like me to do my frontend business on.

I clearly have taken their npm knowledge for granted because I'm suddenly scared about publishing. But I am going to do this!

**Comment by DanielRuf** [comment]
You don't have to be afraid (it's often the excitement and it feels great). If you need any further help just let me know.

With the support of great colleagues everything is possible together as a team =)

Let's make one (little) step after another and no developer is perfect (I am currently contributing to many projects and try to improve OSS quality in several ways).

I'm excited to see your next projects. 👍

**Comment by dotnetCarpenter** [comment]
@cyanharlow perhaps you could just `push` your source files and someone can make a PR with the webpack bundler or whatever is in fashion.

I think it's a very useful project but I won't use it without source files.

**Comment by DanielRuf** [comment]
> I think it's a very useful project but I won't use it without source files.

That's a bit harsh.
In general you can run the code through a beautifier like https://beautifier.io/ and get some cleaned up code.

And then you can run it through https://lebab.unibtc.me/editor

**Comment by dotnetCarpenter** [comment]
I'm sorry if it sounded harsh. I didn't mean to. But reverse engineering, even with the tools you suggested...

```js
function textToCSSFont(r, o) {
    function t() {
        for (var r = "", o = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", t = 0; t < 4; t++) r += o.charAt(Math.floor(Math.random() * o.length));
        return r += Math.round(1e3 * Math.random())
    }

    const e = {
        // alphabet in CSS
    }
    let i = "<style>";
    let s = "";
    o && (o.bold && (s += "font-weight: bold;"), o.italic && (s += "font-style: italic;"), o.underlined && (s += "text-decoration: underline;"));
    for (var b = `<span style="${s}"><i class="azwd">`, a = 0; a < r.length; a++) {
        const n = r.charAt(a);
        const m = t();
        if ("\n" !== n && "\r" !== n && " " !== n) {
            const l = e[`_${n}`] ? e[`_${n}`](m) : "";
            d[`_${m}`] = l, b += `<i class="AZ _${m}"></i>`
        } else b += " " === n ? '</i><i class="AZ _sp"></i><i class="azwd">' : '</i><br/><i class="azwd">'
    }
    for (const h in (b += "</i></span>", d)) d.hasOwnProperty(h) && (i += d[h]);
    return (i += "</style>") + b
```
I'm sorry but it is beyond my capabilities to tweak/debug the above.

**Comment by cyanharlow** [comment]
No apologies needed y'all are absolutely lovely for even giving half a shit about this project. One that admittedly has completely taken a backburner and really _should_ be on npm and kinda embarrassing that it isn't yet

**Comment by cyanharlow** [comment]
i promise i will get to this at some point

**Comment by DanielRuf** [comment]
Let us know if and how we can help here.

**Comment by dotnetCarpenter** [comment]
@cyanharlow If only you could push the source files. For my sake that is all that is needed. Creating a library with webpack, publishing it on NPM, create unit tests and run them on a CI server (e.i. travis) is all nice but it's a lot of work and I assume that we all would want to tweak the library a little. Use it in a project or two, polish it a bit and then yeah, we can do all of the above.
Which while it's a lot of work, I suspect that @DanielRuf has done it a few times before and myself too, so it's not that much to do (once you have done it a few times).

But please, let's just get the source code up on github.

**Comment by DanielRuf** [comment]
I guess some are ignored in https://github.com/cyanharlow/PureCSS-Font/blob/master/.gitignore

**Comment by Angra974** [comment]
Thanks for your hard work :) bye bye G-recaptcha

**Comment by DanielRuf** [comment]
How does this replace reCaptcha which does IP reputation checks?
